config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper_agency.urls", namespace="newspaper_agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper_agency/urls.py

from django.urls import path

from .views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"
    ),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "taxi"

newspaper_agency/models.py
from django.conf import settings
from django.contrib.auth.models import  AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(
        verbose_name="years_of_experience",
        null=True
    )

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        to=Topic,
        on_delete=models.CASCADE,
    )
    publishers = models.ManyToManyField(
        Redactor,
        related_name="newspapers"
    )

    def __str__(self):
        return self.title

newspaper_agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from newspaper_agency.models import Newspaper, Redactor


class NewspaperForm(forms.ModelForm):
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = "__all__"

newspaper_agency/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper_agency.forms import RedactorCreationForm, RedactorUpdateForm, NewspaperForm
from newspaper_agency.models import Topic, Newspaper, Redactor


@login_required
def index(request):
    """View function for the home page of th site"""

    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()
    new_redactors = Redactor.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "new_redactors": new_redactors,
        "num_visits": num_visits + 1
    }

    return render(request, "newspaper_agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "newspaper-agency:topic_list.html"
    paginate_by = 5


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper_agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper_agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper_agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.all().select_related("topic")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper_agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper_agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper_agency:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.all().prefetch_related("newspapers__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper_agency:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper_agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper_agency:redactor-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Newspaper Agency News4All</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-10">
          {% block content %}{% endblock %}

          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="visually-hidden">Previous</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous" tabindex="-1" aria-disabled="true">
            <span aria-hidden="true">&laquo;</span>
            <span class="visually-hidden">Previous</span>
          </a>
        </li>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="visually-hidden">Next</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Next" tabindex="-1" aria-disabled="true">
            <span aria-hidden="true">&raquo;</span>
            <span class="visually-hidden">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'newspaper_agency:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper_agency:redactor-list' %}">All redactors</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper_agency:newspaper-list' %}">All newspapers</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper_agency:topic-list' %}">All topic</a></li>
</ul>

templates/newspaper_agency/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Newspaper agency "News4All"</h1>
    <p>Welcome to the best newspaper website!</p>
    <p>Our agency provides the following:</p>
    <ul>
        <li><strong>Newspapers:</strong> {{ num_newspapers }}</li>
        <li><strong>Redactors:</strong> {{ num_redactors }}</li>
        <li><strong>Topics:</strong> {{ num_topics }}</li>
    </ul>

    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}

templates/newspaper_agency/newspaper_confim_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/newspaper_agency/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.title }}
    <a href="{% url 'newspaper_agency:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'newspaper_agency:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Topic: ({{ newspaper.topic.name }})</p>

  <hr>
  <ul>
    {% for redactor in newspaper.redactors.all %}
      <li>{{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/newspaper_agency/newspaper_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/newspaper_agency/newspaper_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Car list
    <a href="{% url 'newspaper_agency:newspaper-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if newspaper_list %}
    <ul>
      {% for newspaper in newspaper_list %}
        <li>
          <a href="{% url "newspaper_agency:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.id }}</a>
          {{ newspaper.title }} ({{ newspaper.topic.name }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no newspapers in newspaper_agency</p>
  {% endif %}
{% endblock %}

templates/newspaper_agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/newspaper_agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ redactor.username }}
    <a href="{% url 'newspaper_agency:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'newspaper_agency:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">
      Update redactor
    </a>
  </h1>

  <p><strong>First name:</strong> {{ redactor.first_name }}</p>
  <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

  <div class="ml-3">
    <h4>Newspapers</h4>

    {% for newspaper in redactor.newspapers.all %}
        <hr>
        <p><strong>Title:</strong> {{ newspaper.title }}</p>
        <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{newspaper.id}}</p>

    {% empty %}
      <p>No newspapers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/newspaper_agency/redactor_form.html
{% extends "base.html" %}

{% block content %}
  <h1>Create redactor</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/newspaper_agency/redactor_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      Driver List
      <a href="{% url 'newspaper_agency:redactor-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    {% if redactor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for redactor in redactor_list %}
      <tr>
        <td>{{ redactor.id }}</td>
        <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
        <td>{{ redactor.first_name }}</td>
        <td>{{ redactor.last_name }}</td>
        <td>{{ redactor.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no redactors in the service.</p>
    {% endif %}
{% endblock %}

templates/newspaper_agency/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/newspaper_agency/topic_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/newspaper_agency/topic_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Topic List
    <a href="{% url 'newspaper_agency:topic-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if topic_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Topic</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for topic in topic_list %}
        <tr>
          <td>
              {{ topic.id }}
          </td>
          <td>
              {{ topic.name }}
          </td>
          <td>
              <a href="{% url 'newspaper_agency:topic-update' pk=topic.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'newspaper_agency:topic-delete' pk=topic.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no topics in the service.</p>
  {% endif %}
{% endblock %}